name: Auto optimize images & generate sitemap

on:
  push:
    branches: [ main ]
  schedule:
    # 매일 오전 9시 (UTC) 실행
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --prefer-offline --no-audit
          echo "Dependencies installed successfully"

      - name: Generate sitemap
        run: |
          echo "Starting sitemap generation..."
          npm run generate:sitemap
          echo "Sitemap generation completed"

      - name: Generate RSS
        run: |
          echo "Starting RSS generation..."
          npm run generate:rss
          echo "RSS generation completed"

      - name: Optimize images
        run: |
          echo "Starting image optimization..."
          npm run optimize:images
          echo "Image optimization completed"

      - name: Check for changes
        id: verify-changed-files
        run: |
          echo "Checking for file changes..."
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit generated assets
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          echo "Committing changes..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No staged changes to commit"
            exit 0
          fi
          git commit -m "chore(ci): auto-generate sitemap, RSS and optimize images [skip ci]"
          echo "Attempting to push changes..."
          if git push; then
            echo "Push successful"
          else
            echo "Push failed, but workflow continues"
          fi
