name: Auto SEO maintenance

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch: {}

jobs:
  regen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: read
      id-token: write
    concurrency:
      group: auto-seo
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install deps
        run: |
          echo "Installing production deps..."
          npm ci --only=production --prefer-offline --no-audit || echo "npm ci failed"
          npm install --only=production --prefer-offline --no-audit || echo "npm install failed (continuing)"
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq || true
      - name: Run SEO scripts
        run: |
          echo "Running sitemap generation..."
          node generate-sitemap.js || echo "Sitemap generation failed (non-fatal)"
          echo "Running RSS generation..."
          node generate-rss.js || echo "RSS generation failed (non-fatal)"
          echo "Running SEO check..."
          node scripts/seo-check.js || echo "SEO check failed (non-fatal)"
          echo "All SEO scripts completed"
      - name: Commit changes
        id: commit_push
        run: |
          echo "Configuring git..."
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "Adding files..."
          git add sitemap.xml rss.xml posts.json || echo "Some files may not exist"

          echo "Checking for changes..."
          if ! git diff --staged --quiet; then
            echo "Changes detected, committing..."
            git commit -m "chore(seo): regenerate sitemap/rss and run seo-check [skip ci]"
            echo "Pushing changes..."
            if git push origin main; then
              echo "pushed=true" >> $GITHUB_OUTPUT
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "Push failed, checking remote status..."
              git fetch origin
              git status
              echo "pushed=false" >> $GITHUB_OUTPUT
              echo "changed=true" >> $GITHUB_OUTPUT
              echo "Continuing despite push failure"
            fi
          else
            echo "No changes to commit"
            echo "pushed=false" >> $GITHUB_OUTPUT
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Wait for GitHub Pages deployment
        continue-on-error: true
        if: steps.commit_push.outputs.pushed == 'true'
        env:
          REPO: ${{ github.repository }}
          TIMEOUT_MIN: 10
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking Pages build status for $REPO..."
          START=$(date +%s)
          TIMEOUT=$((TIMEOUT_MIN * 60))
          while true; do
            STATUS=$(curl -s \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              "https://api.github.com/repos/${REPO}/pages/builds" | jq -r '.[0].status // "none"')
            if [ "$STATUS" = "built" ]; then
              echo "Pages built successfully"
              break
            fi
            if [ "$STATUS" = "errored" ]; then
              echo "Pages build errored" >&2
              # Create an issue to notify maintainers
              echo '{"title":"Pages build failed for '${REPO}'","body":"The automatic SEO workflow detected a Pages build failure. Please check GitHub Pages and workflow logs. This issue was created by the Auto SEO workflow.","labels":["ci","pages","seo"]}' > /tmp/pages_issue.json
              curl -s -X POST -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${REPO}/issues" -d @/tmp/pages_issue.json || true
              break
            fi
            NOW=$(date +%s)
            ELAPSED=$((NOW - START))
            if [ $ELAPSED -gt $TIMEOUT ]; then
              echo "Pages build did not finish within ${TIMEOUT_MIN} minutes" >&2
              break
            fi
            echo "Current Pages status: $STATUS — waiting..."
            sleep 10
          done
      - name: Workflow summary
        run: |
          echo "--- SEO Maintenance Summary ---"
          if [ -f seo-report.json ]; then
            echo "seo-report.json exists. Showing brief summary:"
            cat seo-report.json | head -n 100 || true
          else
            echo "seo-report.json not found (maybe no issues or script skipped)."
          fi
