name: Auto SEO maintenance

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC

jobs:
  regen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci || true
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq || true
      - name: Run SEO scripts
        run: |
          node generate-sitemap.js
          node generate-rss.js
          node scripts/seo-check.js
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml rss.xml posts.json seo-report.json || true
          if ! git diff --staged --quiet; then
            git commit -m "chore(seo): regenerate sitemap/rss and run seo-check" || true
            git push
          else
            echo "No changes to commit"
          fi
      - name: Wait for GitHub Pages deployment
        env:
          REPO: ${{ github.repository }}
          TIMEOUT_MIN: 10
        run: |
          echo "Checking Pages build status for $REPO..."
          START=$(date +%s)
          TIMEOUT=$((TIMEOUT_MIN * 60))
          while true; do
            STATUS=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${REPO}/pages/builds" | jq -r '.[0].status // "none"')
            if [ "$STATUS" = "built" ]; then
              echo "Pages built successfully"
              break
            fi
            if [ "$STATUS" = "errored" ]; then
              echo "Pages build errored" >&2
              # Create an issue to notify maintainers
              echo '{"title":"Pages build failed for '${REPO}'","body":"The automatic SEO workflow detected a Pages build failure. Please check GitHub Pages and workflow logs. This issue was created by the Auto SEO workflow.","labels":["ci","pages","seo"]}' > /tmp/pages_issue.json
              curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${REPO}/issues" -d @/tmp/pages_issue.json || true
              exit 1
            fi
            NOW=$(date +%s)
            ELAPSED=$((NOW - START))
            if [ $ELAPSED -gt $TIMEOUT ]; then
              echo "Pages build did not finish within ${TIMEOUT_MIN} minutes" >&2
              exit 1
            fi
            echo "Current Pages status: $STATUS — waiting..."
            sleep 10
          done
