name: GitHub Pages Simple Deploy

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --prefer-offline --no-audit || npm install --prefer-offline --no-audit
          echo "Dependencies installed"

      - name: Build CSS (Tailwind)
        run: |
          echo "Building CSS..."
          npm run build:css || echo "CSS build skipped/failed"
          echo "CSS build step finished"

      - name: Generate sitemap
        run: |
          echo "Generating sitemap.xml..."
          npm run generate:sitemap || echo "sitemap generation failed (continuing)"
          echo "sitemap step finished"

      - name: Generate RSS
        run: |
          echo "Generating rss.xml..."
          npm run generate:rss || echo "rss generation failed (continuing)"
          echo "rss step finished"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
